- name : Disable nginx old version
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable nginx nginx:1.24 
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest