- name: Disable default nginx
  ansible.builtin.shell: dnf module disable nginx -y

- name: enable default nginx:1.24
  ansible.builtin.shell: dnf module disable nginx:1.24 -y

- name: install ngink
  ansible.builtin.dnf: 
    name: nginx
    state: latest

- name: copy nginx.conf file
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: service config 
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true

    