- name : Disable nginx old version
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable nginx nginx:1.24 
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy config file
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start nginx
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx