- name: copy repo file
  ansible.builtin.template:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: install rabbitMQ 
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: latest

- name: Add rabbotMQ user
  ansible.builtin.include_role:
    name: common
    tasks_from: add_users

- name: create systemd service
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: restarted 
    enabled: true
