- name: copy mongo repo file to /etc/yum.repo.d/mongo.repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repo.d/mongo.repo

- name: install mongo
  ansible.builtin.dnf:
    name: mongodb-org
    state: latest
- name: replace 127.0.0.1 in mongo conf file
  ansible.builtin.replace:
    path: /etc/mogod.conf
    regexp: 127.0.0.0
    replace: 0.0.0.0

- name: service restart
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: true

    