- name: install mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: enable mysql service
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: true

- name: password encryption change
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
