name: learn-github-actions
on: [push,workflow_dispatch]
jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello

  qa:
    runs-on: ubuntu-latest
    needs:
      - dev
    steps:
      - run: echo Hello

  uat:
    runs-on: ubuntu-latest
    needs:
      - qa
    steps:
      - run: echo Hello

    
